site_name: Actividades
dev_addr: 127.0.0.1:8001
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
    - Individuales:
        - Actividad 1: individual/Actividad_1.md
        - Actividad 2: individual/Actividad_02.md
        - Actividad 3: individual/Actividad_03.md
        - Actividad 4: individual/Actividad_04.md
        - Actividad 5: individual/Actividad_05.md
    - Colaborativas:
        - Actividad 1: todo.md
    - Ejemplos:
        - Actividad 3: individual/Ejemplo_03.md
copyright: ©GMDXX
site_author: GMDXX
